### ISSUE TITLE
VPDE-Net

### ISSUE THREAD

**Issue by AymanTalkhani** [EthanZhu90/ZSL_GAN#3]
Where is the VPDE-Net present in the code? This net was mentioned in the paper but I can't find it anywhere in the code.

**Comment by rahulshekhar97** [comment]
Did you end up finding VPDE-net?

**Comment by AymanTalkhani** [comment]
Nope. Couldn't find it anywhere. Please let me know if anyone does.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
04/02/21,
09:47:10 AM

**Comment by rahulshekhar97** [comment]
My understanding is that if you download the data files they contain the feature vectors after having run it through VPDE-net?

**Comment by AymanTalkhani** [comment]
Yes that's right. I would still like to use the VPDE net to try it out on other datasets though.

**Comment by rahulshekhar97** [comment]
Do you know what pfc stands for in the dataset?
